

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SMS_Rails_development
  pool: 5
  host: localhost
  username: fiddler
  password: password

  
test:
  <<: *default
  database: SMS_Rails_test
  

production:
  <<: *default
  database: SMS_Rails_production
  username: fiddler
  password: password
