

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SMS_Rails_development
  pool: 5
  username: fiddler
  password: 

  
test:
  <<: *default
  database: SMS_Rails_test
  

production:
  <<: *default
  database: SMS_Rails_production
  username: SMS_Rails
  password: <%= ENV['SMS_RAILS_DATABASE_PASSWORD'] %>
